### ISSUE TITLE
Your LaTeX post

### ISSUE THREAD

**Issue by ofenerci** [sam217pa/sam217pa.github.io#2]
Hello,
I was reading your blog and I found very informative (especially, for a person who is undecided which emacs distribution to choose: Spacemacs, Evil Mode, or pure Emacs.). Currently, I am trying to change my lovely editor (Vim) to Emacs and how to use edit LaTeX.

Your post (https://sam217pa.github.io/2016/06/07/using-latex/) mentions that you wrote your thesis by using Tufte Class and Tikz. I am thinking to write my master thesis using Tufte class and use some Tikz drawing. You gave the link to download your thesis from Dropbox but the link is dead. I wonder I may peek into your thesis source code and take some examples from it. 

My second question is that: Which Hugo theme was used in your blog.

Bests,

**Comment by sam217pa** [comment]
Hi, 

(Actually, it wasn't my thesis but what would be the equivalent of an undergrad dissertation, but anyway).

Maybe you can take a look at the following archive, in which I packed my dissertation, with pictures and all, tex files and resulting pdf.
I can't assure you that anything is idiomatic LaTeX, since (1) I had to make tradeoffs between document quality and imposed presentation rules and (2) I was essentially a beginner in LaTeX (still am).
But I do have some fairly complicated Tikz-generated figures in it.
Hope that helps !

- [rapportBib.zip](https://github.com/sam217pa/sam217pa.github.io/files/3266205/rapportBib.zip)

And the theme name is [ghostwriter](https://themes.gohugo.io/ghostwriter/), though I do remember having changed the hardcoded "Red" colors to something that look more "Teal" or something like that.

Regards,
